# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4df883a3bd618dfcbbc9949412d086431c3cd233801146182dabbfdc0f3770028d0d473f7ad83f8c4183174fc30d8eef09f294bea87f3ff0c437c31656cf3d89

test:
  secret_key_base: 16cbe5de6f6f5ce234db75b07fb92b09d0d086409ed4e5c44f360ceb4cbcc04e819ee1ba31c7007652a471c15a31242523eda57e67f95c28fc5d1611b78d79ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
